name: build-and-deploy
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ new-client-release ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.x

      - name: Fetch client release
        id: fetch-client-step
        uses: robinraju/release-downloader@v1.7
        with:
          repository: 'rinfex-holfer/life-is-short-client'
          latest: true
          tarBall: false
          zipBall: true

      - name: Check tag name
        run: echo "${{steps.fetch-client-step.outputs.tag_name}}"

      - name: Check
        run: ls "$GITHUB_WORKSPACE"

      - name: Unzip
        run: unzip "$GITHUB_WORKSPACE/life-is-short-client-${{steps.fetch-client-step.outputs.tag_name}}.zip" -d client-dist

      - name: Remove zip
        run: rm -rf "$GITHUB_WORKSPACE/life-is-short-client-${{steps.fetch-client-step.outputs.tag_name}}.zip"

      - name: Check
        run: ls "$GITHUB_WORKSPACE/client-dist"

      - name: Check
        run: ls "$GITHUB_WORKSPACE"

