name: build-and-deploy
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ new-client-release ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.x

      - name: Fetch client release
        uses: robinraju/release-downloader@v1.7
        with:
          repository: 'rinfex-holfer/life-is-short-client'
          latest: true
          tarBall: false
          zipBall: true
          out-file-path: "client-dist"

      - name: Check
        run: ls "$GITHUB_WORKSPACE"

      - name: Check
        run: ls "$GITHUB_WORKSPACE/client-dist"

